[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part01"
path = "src/bin/part01.rs"

[[bin]]
name = "part02"
path = "src/bin/part02.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
